use_frameworks!

platform :ios, '10.0'

target 'FFPhotosLibrary_Example' do
  pod 'FFPhotosLibrary', :path => '../'
  pod 'FFUITool', :path => '~/myself_github/FFUITool'

#  target 'FFPhotosLibrary_Tests' do
#    inherit! :search_paths
#
#    pod 'Quick', '~> 2.2.0'
#    pod 'Nimble', '~> 10.0.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 9.4.0'
#  end
  
  post_install do |installer_representation|
      installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
              config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
              config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
              config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
              config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
              config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
              config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
          end
      end
  end
  
end
